### ISSUE TITLE
About restricted files 

### ISSUE THREAD

**Issue by lordofwizard** [mtojek/gdriver#1]
Hello i really liked your server but i want to download some shared folder files but the thing is i cannot access the Anyone link. The files are restricted to specific users. Even if i have auth from the same id i cannot download them using your gdriver program what can i do please tell me. it gives this error 
```
Read folder metadata for "17bOYXU3lpoDlg-yYgDPea_frqWbAEY6g"
Error: downloading files failed: can't read folder metadata (ID: 17bOYXU3lpoDlg-yYgDPea_frqWbAEY6g): googleapi: Error 404: File not found: 17bOYXU3lpoDlg-yYgDPea_frqWbAEY6g., notFound
```

**Comment by mtojek** [comment]
There are two actions required to perform before you start using the software:
1. Create and import the client configuration (for the Google Account that has access to the shared folder).
2. Authenticate your personal account to use the gdriver in the context of your own drive.

I assume you did both correctly. Could you please double-check these items:
1. Do you have access to other folders stored in your own Drive? (you can use `gdriver check` for that).
2. Do you have access to `17bOYXU3lpoDlg-yYgDPea_frqWbAEY6g` while navigating there with your browser? The application behaves like the client browser, so it should access same resources.

**Comment by lordofwizard** [comment]
> There are two actions required to perform before you start using the software:
> 
> 1. Create and import the client configuration (for the Google Account that has access to the shared folder).
> 2. Authenticate your personal account to use the gdriver in the context of your own drive.
> 
> I assume you did both correctly. Could you please double-check these items:
> 
> 1. Do you have access to other folders stored in your own Drive? (you can use `gdriver check` for that).
> 2. Do you have access to `17bOYXU3lpoDlg-yYgDPea_frqWbAEY6g` while navigating there with your browser? The application behaves like the client browser, so it should access same resources.

Okay let me check

**Comment by lordofwizard** [comment]
na didn't worked check this i tried this with different folder also i am in the group i can see those files and i can watch them online in 360p. Also the folder is shared in our member party only. I tried this different folder. I can download those files after they are zipped i have authenticated with the same account that have the access to those files. But i cannot generate it's public(anyone with the link) link. 
![gdrive](https://user-images.githubusercontent.com/38832648/100713859-f4548900-33da-11eb-9fcd-581bb759eeff.png)
hope this screen shot will help

**Comment by lordofwizard** [comment]
> There are two actions required to perform before you start using the software:
> 
> 1. Create and import the client configuration (for the Google Account that has access to the shared folder).
> 2. Authenticate your personal account to use the gdriver in the context of your own drive.
> 
> I assume you did both correctly. Could you please double-check these items:
> 
> 1. Do you have access to other folders stored in your own Drive? (you can use `gdriver check` for that).
> 2. Do you have access to `17bOYXU3lpoDlg-yYgDPea_frqWbAEY6g` while navigating there with your browser? The application behaves like the client browser, so it should access same resources.
I have the access while browsing with my browser. I can download the files or view them.

**Comment by mtojek** [comment]
Are you referring to the "Anyone link"? I tried to reproduce it this way:

on account A:
1. I created a directory on Drive and put some files there.
2. I shared the directory as "Anyone link".

on account B:
1. I opened the shared link in the browser.
2. I used the gdriver with the folder ID.

It worked without any issues. Could you write down steps to reproduce your issue? Maybe you're using a different mode I didn't try out.

**Comment by mtojek** [comment]
Anyway, didn't reproduce it so far, so resolving.
