### ISSUE TITLE
didn't close resp.Body

### ISSUE THREAD

**Issue by liamvdv** [mtojek/gdriver#2]
Hi mtojek, 
I'm building something with the Google Drive API and wanted to see the idiomatic way to download a file, when I stumbled upon this project.
If I'm not mistaken, then you forgot to close the resp.Body in [downloadFileData()](https://github.com/mtojek/gdriver/blob/a20a4628930386cfbd3289c831fde80b34bfb38f/internal/download/files_download.go#L57), which leds to a resource leak. More specificially, the connection isn't reused and thus the file descriptor isn't freed. 
> If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close. If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request. [more](https://golang.org/pkg/net/http/#Client.Do)

To fix this, add `defer resp.Body.Close()` after you check the error of `...Download()`.
Have a nice day! :)

**Comment by mtojek** [comment]
Hey Liam,

thanks for the report, let me take a look.

**Comment by mtojek** [comment]
Thank you for spotting this bug! Have a nice evening :)
